server:
    host: 0.0.0.0
    port: 5000
    debug: False
logging:
    location: logs/ospgbp.log
    level: DEBUG
things:
    - a rocket
    - a drone
    - a pretty cocky  robot
    - I modify that digital photo frame I got last christmas into something
    - something that uses TensorFlow
    - a dodgy-looking USB drive
    - some catapult launchy thing
    - I convert this dusty old rubish bin I found in the shed into something
    - a 1990s style website
    - a modified 2.99 Home Bargains desk fan
    - a RESTful API that doesn't follow the OpenAPI standard
    - a life-size replica of Gandalf
    - one of those sentinel things from No Mans Sky
    - a version of DDOSx that actually works
actions:
    - hastily builds
    - generates
    - throws togeather
    - magically finds
    - yeets
    - secretly buries something in my neighbour's back garden, maybe something like
    - shouts "should have gone to Specsavers" at
    - plays calming sounds while showing a video of
    - contemplates the meaning of
items:
    - a stranger's pet cat
    - a doggo
    - some weird cat/dog hybrid
    - my sister's pet hamster
    - one of those inferior iPhone things
    - Stephen Crow
    - my car keys
    - the long lost TV remote
    - my annoying little brother
    - A Dell R730XD pulled from a random rack in the DC
    - this rusty old spoon I found
    - complete and utter disappointment
    - whatever that thing over there is
languages:
    - an old Sinclair ZX Spectrum 48K
    - a Nintendo Wii
    - an Atari ST
    - various random tones captured from an old tape recorder
    - Python
    - Rust
    - Bash
    - Ansible
    - C++
    - HTML
    - CSS
    - JavaScript
    - Java 
    - Windows Movie Maker
